config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :todos
  root "todos#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

	validates_presence_of :title, :due_date

	def can_destroy
		if due_date > Date.today
			true
		else
			false
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :set_todo, :only => [:show, :edit, :update, :destroy]

	def index
		@todos = Todo.order(due_date: :asc)
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			redirect_to todos_url
		else
			render :new
		end
	end

	def show

	end

	def edit

	end

	def update
		if @todo.update_attributes(todo_params)
			redirect_to todo_path(@todo)
		else
			render :edit
		end
	end

	def destroy
		if @todo.can_destroy
				@todo.destroy
			redirect_to todos_url
		else
			flash[:alert] = 'Mission is overdue, can\'t be deleted!'
			redirect_to todos_url
		end
	end
	


	private

	def todo_params
		params.require(:todo).permit(:title, :due_date, :note)
	end

	def set_todo
		@todo = Todo.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
# :nodoc:
module TodosHelper
  # 回傳刪除按鈕
  def todo_delete_button(todo)
    # 無法刪除的 todos 直接回傳 nil
    return unless todo.can_destroy
    link_to '<span class="glyphicon glyphicon-remove"></span>DEL'.html_safe, todo_path(todo), class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Delete this item ?' }
  end

  # 回傳編輯按鈕
  def todo_edit_button(todo)
    link_to '<span class= "glyphicon glyphicon-edit"></span>EDIT'.html_safe, edit_todo_path(todo), class: 'btn btn-info btn-xs' 
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="errorbox">
	<% if @todo.errors.present? %>
		<ul>
			<% @todo.errors.each do |error, message| %>
					<li><%= "#{error.capitalize} #{message}" %></li>
				<% end %>
		</ul>
	<% end %>
</div>

<div class="itembox">
	<%= form_for @todo do |f| %>
		<%= f.label :title, 'Mission' %>
		<br>
		<%= f.text_area :title %>
		<br>
		<%= f.label :due_date, 'Due date' %>
		<br>
		<%= f.date_select :due_date %>
		<br>
		<%= f.label :note, 'Note' %>
		<br>
		<%= f.text_area :note %>
		<br>
		<div class="itembox_btn">
			<%= f.submit button, class: 'btn btn-success' %>
      <%= link_to 'BACK', :back, class: 'btn btn-default' %>
		</div>
	<% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form", locals: { button: 'UPDATE' }%>

app/views/todos/index.html.erb
<div class="container">
    <h1>To Do List</h1>
    <div class="row col-md-6 col-md-offset-2 custyle ">
    <table class="table table-striped custab">
    <thead>
    <%= link_to '<b>+</b>ADD'.html_safe, new_todo_path, class: 'btn btn-primary btn-xs pull-right'%>
        <tr>
            <th>Date</th>
            <th>Mission</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
        <% @todos.each do |todo| %>
            <tr>
                <td><%= todo.due_date %></td>
                <td><%= link_to todo.title, todo_path(todo) %></td>
                <td class="text-center">
                    <%= todo_edit_button(todo) %>
                    <%= todo_delete_button(todo) %>
                </td>
            </tr>
        <% end %>
    </table>
    </div>
</div>

app/views/todos/new.html.erb
<%= render :partial => "form", locals: { button: 'NEW'} %>

app/views/todos/show.html.erb
<div class="itembox">
	<p class ="title"><%= @todo.title %></p><br>
	<p class="due_date"><%= @todo.due_date %></p><br>
	<%= simple_format @todo.note, class: 'note' %>
	<div class="itembox_btn">
    <%= todo_edit_button(@todo) %><br>
    <%= link_to 'BACK', todos_path, class: 'btn btn-default' %>
  </div>
</div>